import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('Missing env vars: VITE_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const CATEGORIES = [
  "Diagnostic & Monitoring",
  "Clinical & Hospital",
  "Mobility & Rehabilitation",
  "Laboratory",
  "Emergency & First Aid"
];

const products = [
  {
    name: 'MediHub Pro Digital BP Monitor',
    slug: 'medihub-pro-digital-bp-monitor',
    category: 'Diagnostic & Monitoring',
    price: 4500,
    stock: 50,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=BP+Monitor',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=BP+Monitor'],
    short_description: 'Clinically accurate upper arm blood pressure monitor with large LCD.',
    long_description: 'The MediHub Pro Digital BP Monitor offers precise readings with an easy-to-read display. Features irregular heartbeat detection, 2-user memory, and a comfortable wide-range cuff suitable for most arm sizes.',
    specifications: { 'Type': 'Upper Arm', 'Power': '4xAA Batteries', 'Memory': '2 users x 60 readings' },
    rating: 4.8,
    reviews: 124,
    featured: true,
  },
  {
    name: 'Fingertip Pulse Oximeter',
    slug: 'fingertip-pulse-oximeter',
    category: 'Diagnostic & Monitoring',
    price: 2500,
    stock: 120,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=Oximeter',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=Oximeter'],
    short_description: 'Accurate SpO2 and pulse rate measurement in seconds.',
    long_description: 'Compact and lightweight, this Pulse Oximeter is perfect for sports enthusiasts and health management.',
    specifications: { 'Display': 'OLED', 'Auto-off': 'Yes', 'Battery': '2xAAA' },
    rating: 4.6,
    reviews: 89,
    featured: false,
  },
  {
    name: 'AccuSmart Glucometer Kit',
    slug: 'accusmart-glucometer-kit',
    category: 'Diagnostic & Monitoring',
    price: 3200,
    stock: 45,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=Glucometer',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=Glucometer'],
    short_description: 'Complete blood glucose monitoring system with strips and lancets.',
    long_description: 'Keep your blood sugar in check with the AccuSmart Glucometer. Fast 5-second results.',
    specifications: { 'Result Time': '5 seconds', 'Sample Size': '0.6 µL', 'Coding': 'No coding required' },
    rating: 4.7,
    reviews: 210,
    featured: false,
  },
  {
    name: 'Infrared Forehead Thermometer',
    slug: 'infrared-forehead-thermometer',
    category: 'Diagnostic & Monitoring',
    price: 3800,
    stock: 80,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=Thermometer',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=Thermometer'],
    short_description: 'Contactless digital thermometer for hygienic fever screening.',
    long_description: 'Professional grade non-contact infrared thermometer. Ideal for hospitals, clinics, and home use.',
    specifications: { 'Distance': '1-5cm', 'Memory': '32 sets', 'Response': '1 second' },
    rating: 4.5,
    reviews: 56,
    featured: false,
  },
  {
    name: 'Portable ECG Monitor',
    slug: 'portable-ecg-monitor',
    category: 'Diagnostic & Monitoring',
    price: 18500,
    stock: 15,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=ECG+Monitor',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=ECG+Monitor'],
    short_description: 'Handheld ECG monitor for instant heart rhythm analysis.',
    long_description: 'Detects arrhythmias and heart irregularities anywhere, anytime.',
    specifications: { 'Channels': 'Single', 'Battery': 'Rechargeable Li-ion', 'Connectivity': 'USB' },
    rating: 4.9,
    reviews: 32,
    featured: false,
  },
  {
    name: 'Hydraulic Examination Bed',
    slug: 'hydraulic-examination-bed',
    category: 'Clinical & Hospital',
    price: 45000,
    stock: 5,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=Exam+Bed',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=Exam+Bed'],
    short_description: 'Adjustable height examination couch for clinical use.',
    long_description: 'Heavy-duty steel frame with comfortable padding.',
    specifications: { 'Max Load': '200kg', 'Adjustment': 'Hydraulic Foot Pump', 'Material': 'PU Leather' },
    rating: 5.0,
    reviews: 12,
    featured: false,
  },
  {
    name: 'Heavy Duty Suction Machine',
    slug: 'heavy-duty-suction-machine',
    category: 'Clinical & Hospital',
    price: 28000,
    stock: 10,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=Suction+Machine',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=Suction+Machine'],
    short_description: 'Powerful suction unit for surgical and emergency use.',
    long_description: 'Designed for absorbing thick liquids such as blood and phlegm.',
    specifications: { 'Flow Rate': '20L/min', 'Bottle': '2500ml x 2', 'Noise': '<60dB' },
    rating: 4.8,
    reviews: 8,
    featured: false,
  },
  {
    name: 'Tabletop Autoclave Class B',
    slug: 'tabletop-autoclave-class-b',
    category: 'Clinical & Hospital',
    price: 120000,
    stock: 3,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=Autoclave',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=Autoclave'],
    short_description: '23L Sterilizer for medical and dental instruments.',
    long_description: 'Fully automatic front-loading autoclave with vacuum cycles.',
    specifications: { 'Capacity': '23 Liters', 'Chamber': 'Stainless Steel', 'Programs': '5 Preset' },
    rating: 4.9,
    reviews: 5,
    featured: false,
  },
  {
    name: 'Multi-Parameter Patient Monitor',
    slug: 'multi-parameter-patient-monitor',
    category: 'Clinical & Hospital',
    price: 85000,
    stock: 7,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=Patient+Monitor',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=Patient+Monitor'],
    short_description: '12-inch screen monitor for ICU and OR.',
    long_description: 'Monitors ECG, NIBP, SpO2, Resp, and Temp. High-resolution color TFT display.',
    specifications: { 'Screen': '12.1" TFT', 'Battery': '4 hours backup', 'Alarm': 'Visual & Audio' },
    rating: 4.7,
    reviews: 15,
    featured: false,
  },
  {
    name: 'Nebulizer Compressor Kit',
    slug: 'nebulizer-compressor-kit',
    category: 'Clinical & Hospital',
    price: 4500,
    stock: 40,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=Nebulizer',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=Nebulizer'],
    short_description: 'Effective medication delivery for respiratory conditions.',
    long_description: 'Compact compressor nebulizer for efficient management of asthma, COPD, and other respiratory disorders.',
    specifications: { 'Particle Size': '3 µm', 'Noise': 'Low', 'Operation': 'One-button' },
    rating: 4.6,
    reviews: 98,
    featured: false,
  },
  {
    name: 'Foldable Steel Wheelchair',
    slug: 'foldable-steel-wheelchair',
    category: 'Mobility & Rehabilitation',
    price: 15000,
    stock: 25,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=Wheelchair',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=Wheelchair'],
    short_description: 'Durable chrome-plated steel wheelchair with leather seat.',
    long_description: 'Standard lightweight wheelchair with fixed armrests and footrests.',
    specifications: { 'Frame': 'Chrome Steel', 'Seat Width': '46cm', 'Max Weight': '100kg' },
    rating: 4.8,
    reviews: 45,
    featured: true,
  },
  {
    name: 'Aluminum Walker with Wheels',
    slug: 'aluminum-walker-wheels',
    category: 'Mobility & Rehabilitation',
    price: 6500,
    stock: 30,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=Walker',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=Walker'],
    short_description: 'Height adjustable folding walker with front wheels.',
    long_description: 'Provides stability and support for those needing assistance walking.',
    specifications: { 'Material': 'Anodized Aluminum', 'Height': 'Adjustable', 'Type': 'Reciprocal' },
    rating: 4.7,
    reviews: 33,
    featured: false,
  },
  {
    name: 'Adjustable Elbow Crutches (Pair)',
    slug: 'adjustable-elbow-crutches',
    category: 'Mobility & Rehabilitation',
    price: 3500,
    stock: 60,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=Crutches',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=Crutches'],
    short_description: 'Ergonomic aluminum forearm crutches.',
    long_description: 'Double adjustable crutches for optimal fit.',
    specifications: { 'Material': 'Aluminum', 'Cuff': 'Open', 'Weight Capacity': '110kg' },
    rating: 4.5,
    reviews: 28,
    featured: false,
  },
  {
    name: 'Binocular Compound Microscope',
    slug: 'binocular-compound-microscope',
    category: 'Laboratory',
    price: 35000,
    stock: 12,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=Microscope',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=Microscope'],
    short_description: 'Professional biological microscope for lab analysis.',
    long_description: 'High-quality optical system with 4 objectives (4x, 10x, 40x, 100x oil).',
    specifications: { 'Head': 'Binocular Sliding', 'Magnification': '40x - 1000x', 'Light': 'LED Adjustable' },
    rating: 4.9,
    reviews: 14,
    featured: false,
  },
  {
    name: 'Digital Lab Centrifuge',
    slug: 'digital-lab-centrifuge',
    category: 'Laboratory',
    price: 22000,
    stock: 8,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=Centrifuge',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=Centrifuge'],
    short_description: '8-place rotor centrifuge with timer and speed control.',
    long_description: 'Low speed benchtop centrifuge for separation of blood and urine samples.',
    specifications: { 'Max Speed': '4000 RPM', 'Capacity': '8 x 15ml', 'Timer': '0-99 mins' },
    rating: 4.7,
    reviews: 9,
    featured: false,
  },
  {
    name: 'Professional First Aid Kit',
    slug: 'professional-first-aid-kit',
    category: 'Emergency & First Aid',
    price: 4500,
    stock: 100,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=First+Aid+Kit',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=First+Aid+Kit'],
    short_description: 'Comprehensive kit for home, office, or vehicle.',
    long_description: 'Contains essential supplies for treating minor injuries.',
    specifications: { 'Pieces': '120+', 'Case': 'Hard Plastic', 'Standard': 'KEBS Approved' },
    rating: 4.8,
    reviews: 150,
    featured: true,
  },
  {
    name: 'Medical Oxygen Cylinder (10L)',
    slug: 'medical-oxygen-cylinder-10l',
    category: 'Emergency & First Aid',
    price: 18000,
    stock: 20,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=Oxygen+Cylinder',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=Oxygen+Cylinder'],
    short_description: 'Refillable steel oxygen tank with regulator.',
    long_description: 'Seamless steel cylinder for medical oxygen storage.',
    specifications: { 'Capacity': '10 Liters', 'Material': 'Steel', 'Valve': 'Standard Medical' },
    rating: 5.0,
    reviews: 40,
    featured: false,
  },
  {
    name: 'Automated External Defibrillator (AED)',
    slug: 'aed-defibrillator',
    category: 'Emergency & First Aid',
    price: 180000,
    stock: 4,
    image: 'https://placehold.co/600x600/e0f2fe/0369a1?text=AED',
    images: ['https://placehold.co/600x600/e0f2fe/0369a1?text=AED'],
    short_description: 'Life-saving device for sudden cardiac arrest.',
    long_description: 'Portable AED with voice prompts for untrained users.',
    specifications: { 'Waveform': 'Biphasic', 'Battery': '5 Year Standby', 'IP Rating': 'IP55' },
    rating: 5.0,
    reviews: 7,
    featured: false,
  },
];

async function seed() {
  console.log('Seeding products...');
  const { data, error } = await supabase.from('products').upsert(products, { onConflict: 'slug' });
  if (error) {
    console.error('Error seeding products:', error);
    process.exit(1);
  }
  console.log(`Inserted ${data?.length || 0} products successfully.`);
  process.exit(0);
}

seed();
